context:
  version: 0.6.5

package:
  name: esgpull
  version: '{{ version }}'

source:
  - git_url: https://github.com/ESGF/esgf-download.git
    git_rev: '{{ version }}'
    git_depth: 1

build:
  noarch: python
  number: 1
  script: python -m pip install --ignore-installed .
  # script: pdm install --no-isolation
  include_recipe: false
  entry_points:
    - esgpull = esgpull.cli:main

requirements:
  host:
    - python >=3.10
    - setuptools
    - pdm
    - pdm-pep517
    - pdm-backend

  run:
    - python >=3.10
    - MyProxyClient >=2.1.0
    - aiofiles >=22.1.0
    - alembic >=1.8.1
    - click >=8.1.3
    - click-params ==0.3.0
    - click-option-group ==0.5.3
    - httpx >=0.23.0
    - nest-asyncio >=1.5.6
    - pyOpenSSL >=22.1.0
    - pyyaml >=6.0
    - tomlkit >=0.11.5
    - rich >=12.6.0
    - sqlalchemy >=2.0.0b2
    - setuptools >=65.4.1
    - aiostream >=0.4.5
    - attrs >=22.1.0
    - cattrs >=22.2.0
    - platformdirs >=2.6.2
    - pyparsing >=3.0.9
    - openssl >=1.1.1s

test:
  imports:
    - esgpull

  commands:
    - esgpull -h
