"""update tables

Revision ID: 0.2.0
Revises: 0.1.0
Create Date: 2022-11-15 16:36:40.167779

"""

# revision identifiers, used by Alembic.
revision = "0.2.0"
down_revision = "0.1.0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
