"""update tables

Revision ID: 0.3.7
Revises: 0.3.6
Create Date: 2023-04-03 11:42:09.069300

"""


# revision identifiers, used by Alembic.
revision = "0.3.7"
down_revision = "0.3.6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
