"""update tables

Revision ID: 0.3.6
Revises: 0.3.5
Create Date: 2023-03-20 16:50:37.655296

"""


# revision identifiers, used by Alembic.
revision = "0.3.6"
down_revision = "0.3.5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
