"""update tables

Revision ID: 0.3.8
Revises: 0.3.7
Create Date: 2023-04-13 11:39:58.664284

"""


# revision identifiers, used by Alembic.
revision = "0.3.8"
down_revision = "0.3.7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
