"""update tables

Revision ID: 0.3.5
Revises: 0.3.4
Create Date: 2023-03-16 09:38:48.791464

"""

# revision identifiers, used by Alembic.
revision = "0.3.5"
down_revision = "0.3.4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
