"""update tables

Revision ID: 0.3.2
Revises: 0.3.1
Create Date: 2023-03-14 11:27:55.617982

"""


# revision identifiers, used by Alembic.
revision = "0.3.2"
down_revision = "0.3.1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
