"""update tables

Revision ID: 0.3.1
Revises: 0.3.0
Create Date: 2023-03-14 11:06:43.639042

"""

# revision identifiers, used by Alembic.
revision = "0.3.1"
down_revision = "0.3.0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
