"""update tables

Revision ID: 0.4.0
Revises: 0.3.8
Create Date: 2023-05-02 11:52:41.283723

"""

# revision identifiers, used by Alembic.
revision = "0.4.0"
down_revision = "0.3.8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
