"""update tables

Revision ID: 0.5.2
Revises: 0.5.1
Create Date: 2023-06-06 14:13:19.695120

"""

# revision identifiers, used by Alembic.
revision = "0.5.2"
down_revision = "0.5.1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
