"""update tables

Revision ID: 0.5.5
Revises: 0.5.4
Create Date: 2023-06-23 15:21:08.251368

"""

# revision identifiers, used by Alembic.
revision = "0.5.5"
down_revision = "0.5.4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
