"""update tables

Revision ID: 0.5.1
Revises: 0.5.0
Create Date: 2023-05-17 18:09:56.258545

"""


# revision identifiers, used by Alembic.
revision = "0.5.1"
down_revision = "0.5.0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
