"""update tables

Revision ID: 0.5.4
Revises: 0.5.3
Create Date: 2023-06-13 11:43:15.867306

"""

# revision identifiers, used by Alembic.
revision = "0.5.4"
down_revision = "0.5.3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
