"""update tables

Revision ID: 0.5.0
Revises: 0.4.0
Create Date: 2023-05-05 17:10:57.525968

"""


# revision identifiers, used by Alembic.
revision = "0.5.0"
down_revision = "0.4.0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
