"""update tables

Revision ID: 0.6.0
Revises: 0.5.5
Create Date: 2023-07-28 15:01:40.702583

"""

# revision identifiers, used by Alembic.
revision = "0.6.0"
down_revision = "0.5.5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
