"""update tables

Revision ID: 0.6.4
Revises: 0.6.3
Create Date: 2024-07-09 11:04:30.762439

"""

# revision identifiers, used by Alembic.
revision = "0.6.4"
down_revision = "0.6.3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
