"""update tables

Revision ID: 0.6.3
Revises: 0.6.2
Create Date: 2024-06-13 11:48:48.097943

"""

# revision identifiers, used by Alembic.
revision = "0.6.3"
down_revision = "0.6.2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
