"""update tables

Revision ID: 0.6.1
Revises: 0.6.0
Create Date: 2023-07-28 18:40:20.911726

"""

# revision identifiers, used by Alembic.
revision = "0.6.1"
down_revision = "0.6.0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
