"""empty message

Revision ID: 3cd9d12ba8ae
Revises: 0.9.3
Create Date: 2025-11-20 11:13:40.527825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd9d12ba8ae'
down_revision = '0.9.3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backend', sa.Enum('solr', 'stac', name='apibackend'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_column('backend')

    # ### end Alembic commands ###
