"""empty message

Revision ID: 58409c37ff64
Revises: 0.9.2
Create Date: 2025-09-17 16:53:10.595283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58409c37ff64'
down_revision = '0.9.2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backend', sa.Enum('solr', 'stac', name='apibackend'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_column('backend')

    # ### end Alembic commands ###
