"""empty message

Revision ID: fbce12002e02
Revises: 0.9.6
Create Date: 2026-02-13 12:09:52.734874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbce12002e02'
down_revision = '0.9.6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backend', sa.Enum('solr', 'stac', name='apibackend'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_column('backend')

    # ### end Alembic commands ###
