name: tests

on:
  push:
    branches:
      - main
    paths:
      - "*.py"
      - esgpull/**
      - tests/**
      - .github/workflows/ci.yml

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@main
        name: setup pdm
        with:
          python-version: 3.10.0  # Version range or exact version of a Python version to use, the same as actions/setup-python
          architecture: x64    # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          version: 2.1.5       # The version of PDM to install. Leave it as empty to use the latest version from PyPI
          prerelease: false     # Allow prerelease versions to be installed
          enable-pep582: true  # Enable PEP 582 package loading globally

      - name: install dependencies
        run: pdm install

      - name: run lints
        run: pdm run lint

      - name: run tests
        run: pdm run test
